---
apiVersion: v1
data:
  tls.crt: {{.Values.git.regional.tls_cert}}
  tls.key: {{.Values.git.regional.tls_key}}
kind: Secret
metadata:
  name: gitlab-tls-secret
  namespace: {{ required "namespace" .Values.git.regional.namespace }}
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-regional-ingress
  namespace: {{ required "namespace" .Values.git.regional.namespace }}
  labels:
    app: gitlab
  annotations:    
    nginx.ingress.kubernetes.io/service-upstream: "true"  
spec:
  ingressClassName: {{ .Values.git.regional.ingressClassName }}
  rules:
  - host: {{ .Values.git.regional.host }}
    http:
      paths:
      - backend:
          service:
            name: gitlab-regional-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - {{ .Values.git.regional.host }}
      secretName: gitlab-tls-secret
